FROM nginx:latest

# Install Certbot
RUN apt-get update && \
    apt-get install -y certbot python3-certbot-nginx

# Copy your nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Obtain SSL certificate (this is just an example, you need to replace example.com with your domain)
# RUN certbot --nginx -d example.com -d www.example.com --non-interactive --agree-tos -m your-email@example.com

# Command to start nginx
CMD ["nginx", "-g", "daemon off;"]
