name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build all Docker images
        run: |
          for dockerfile in $(ls Dockerfile.*); do
            service_name=$(echo $dockerfile | cut -d'.' -f2)
            docker build . -f $dockerfile -t my-image-$service_name:$(date +%s)
          done
